ACME/Controllers/EventsController.cs
using HrProperty.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ACME.Controllers
{
    public class EventsController : BaseController
    {
        // GET: Events
        public ActionResult Events()
        {
            return View();
        }

        public ActionResult AddEvent(int? id)
        {
            FL_MASJID objmsjidprop = new FL_MASJID();
            if (id > 0)
            {
                objmsjidprop.MAsjid_ID = 1;
                objmsjidprop.Masjid_Location = "New York";
                objmsjidprop.Masjid_Title = "Event Title Name";
                objmsjidprop.Masjid_Descr = "New Event Description";
                objmsjidprop.Masjid_Lat = Convert.ToDecimal(1.2);
                objmsjidprop.Masjid_Lon = Convert.ToDecimal(1.2);
                objmsjidprop.Masjid_Descr = "Description Of Event";
                objmsjidprop.Masjid_Location = "New York";
                objmsjidprop.Rating = Convert.ToDecimal(4);

            }
            return PartialView("_AddEvent", objmsjidprop);

        }
    }
}

ACME/Controllers/MasjidController.cs
using ACME.Controllers_WebApi;
using BLL.Setups;
using HrProperty.Models;
using Newtonsoft.Json;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Http;
using System.Web.Http.Results;
using System.Web.Mvc;

namespace ACME.Controllers
{
    public class MasjidController : BaseController
    {
        // GET: Masjid
        MASJID_BLL objmsjd;
        MasjidApiController _objapimsjid;
        public ActionResult Masjid()
        {
            
            _objapimsjid = new MasjidApiController();
            IHttpActionResult response = _objapimsjid.GetAllMAsjid();
            var content =response as OkNegotiatedContentResult<ResponseClass>;
            List<FL_MASJID> listmsjid = new List<FL_MASJID>();

            ResponseClass objres = (content.Content);
            var respose =objres.ResponseObject;
            if (respose.ToString().Length>0)
            {
                listmsjid = ((IEnumerable)respose).Cast<FL_MASJID>().ToList();
            }
            return View(listmsjid);
        }

        public ActionResult AddMasjid(int? id)
        {
            FL_MASJID objmsjidprop = new FL_MASJID();
            if (id > 0)
            {
                objmsjidprop.MAsjid_ID = 1;
                objmsjidprop.Masjid_Location = "New York";
                objmsjidprop.Masjid_Title = "New Masjid";
                objmsjidprop.Masjid_Lat = Convert.ToDecimal(1.2);
                objmsjidprop.Masjid_Lon = Convert.ToDecimal(1.2);
                objmsjidprop.Masjid_Descr = "Description Of Masjid";
                objmsjidprop.Masjid_Location = "New York";
                objmsjidprop.Rating = Convert.ToDecimal(4);

            }
            return PartialView("AddMasjid", objmsjidprop);

        }

        [System.Web.Http.HttpPost]
        public JsonResult AddUpdate(FL_MASJID objfrom)
        {
            try
            {
                return Json(new { Login = false, statuscode = 400, msg = "", url = "/Account/Login" }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {
                return Json(new { Login = false, statuscode = 400, msg = ex.Message, url = "/Account/Login" }, JsonRequestBehavior.AllowGet);

            }
        }
    }
}

ACME/Views/Events/Events.cshtml
@{
    ViewBag.Title = "Event";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Events</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Events</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>


<section class="content">
    <div class="row">
        <div class="col-12">

            <div class="card">
                <div class="card-header">
                    <h3 class="card-title pull-right"><input type="button" id="btnAddmsjid" class="btn btn-primary" value="Add New" /></h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Event Name</th>
                                <th>Event Date Urdu</th>
                                <th>Event Date</th>
                                <th>Created By</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Trident</td>
                                <td>
                                    Internet
                                    Explorer 4.0
                                </td>
                                <td>Win 95+</td>
                                <td> 4</td>
                                <td>
                                    <div class="row col-sm-12">
                                        <div class="col-sm-6">
                                            <a href="#" class="text-info" onclick="ShowProduct('ProductId')"><i class="fa fa-eye"></i></a>
                                        </div>

                                        <div class="col-sm-6">
                                            <a href="#" class="text-danger" onclick="ConfirmToDelete('product.ProductId')"><i class="fa fa-trash"></i></a>
                                            <input type="submit" class="d-none" />
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>Trident</td>
                                <td>
                                    Internet
                                    Explorer 5.0
                                </td>
                                <td>Win 95+</td>
                                <td>5</td>
                                <td>
                                    <div class="row col-sm-12">
                                        <div class="col-sm-6">
                                            <a href="#" class="text-info" onclick="ShowProduct('ProductId')"><i class="fa fa-eye"></i></a>
                                        </div>

                                        <div class="col-sm-6">
                                            <a href="#" class="text-danger" onclick="ConfirmToDelete('product.ProductId')"><i class="fa fa-trash"></i></a>
                                            <input type="submit" class="d-none" />
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>Trident</td>
                                <td>
                                    Internet
                                    Explorer 5.5
                                </td>
                                <td>Win 95+</td>
                                <td>5.5</td>
                                <td>
                                    <div class="row col-sm-12">
                                        <div class="col-sm-6">
                                            <a href="#" class="text-info" onclick="ShowProduct('ProductId')"><i class="fa fa-eye"></i></a>
                                        </div>

                                        <div class="col-sm-6">
                                            <a href="#" class="text-danger" onclick="ConfirmToDelete('product.ProductId')"><i class="fa fa-trash"></i></a>
                                            <input type="submit" class="d-none" />
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>Trident</td>
                                <td>
                                    Internet
                                    Explorer 6
                                </td>
                                <td>Win 98+</td>
                                <td>6</td>
                                <td>
                                    <div class="row col-sm-12">
                                        <div class="col-sm-6">
                                            <a href="#" class="text-info" onclick="ShowProduct('ProductId')"><i class="fa fa-eye"></i></a>
                                        </div>

                                        <div class="col-sm-6">
                                            <a href="#" class="text-danger" onclick="ConfirmToDelete('product.ProductId')"><i class="fa fa-trash"></i></a>
                                            <input type="submit" class="d-none" />
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>Trident</td>
                                <td>Internet Explorer 7</td>
                                <td>Win XP SP2+</td>
                                <td>7</td>
                                <td>
                                    <div class="row col-sm-12">
                                        <div class="col-sm-6">
                                            <a href="#" class="text-info" onclick="ShowProduct('ProductId')"><i class="fa fa-eye"></i></a>
                                        </div>

                                        <div class="col-sm-6">
                                            <a href="#" class="text-danger" onclick="ConfirmToDelete('product.ProductId')"><i class="fa fa-trash"></i></a>
                                            <input type="submit" class="d-none" />
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>Trident</td>
                                <td>AOL browser (AOL desktop)</td>
                                <td>Win XP</td>
                                <td>6</td>
                                <td>
                                    <div class="row col-sm-12">
                                        <div class="col-sm-6">
                                            <a href="#" class="text-info" onclick="ShowProduct('ProductId')"><i class="fa fa-eye"></i></a>
                                        </div>

                                        <div class="col-sm-6">
                                            <a href="#" class="text-danger" onclick="ConfirmToDelete('product.ProductId')"><i class="fa fa-trash"></i></a>
                                            <input type="submit" class="d-none" />
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>Gecko</td>
                                <td>Firefox 1.0</td>
                                <td>Win 98+ / OSX.2+</td>
                                <td>1.7</td>
                                <td>
                                    <div class="row col-sm-12">
                                        <div class="col-sm-6">
                                            <a href="#" class="text-info" onclick="ShowProduct('ProductId')"><i class="fa fa-eye"></i></a>
                                        </div>

                                        <div class="col-sm-6">
                                            <a href="#" class="text-danger" onclick="ConfirmToDelete('product.ProductId')"><i class="fa fa-trash"></i></a>
                                            <input type="submit" class="d-none" />
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>Gecko</td>
                                <td>Firefox 1.5</td>
                                <td>Win 98+ / OSX.2+</td>
                                <td>1.8</td>
                                <td>
                                    <div class="row col-sm-12">
                                        <div class="col-sm-6">
                                            <a href="#" class="text-info" onclick="ShowProduct('ProductId')"><i class="fa fa-eye"></i></a>
                                        </div>

                                        <div class="col-sm-6">
                                            <a href="#" class="text-danger" onclick="ConfirmToDelete('product.ProductId')"><i class="fa fa-trash"></i></a>
                                            <input type="submit" class="d-none" />
                                        </div>
                                    </div>
                                </td>
                            </tr>

                        </tbody>

                    </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>


<div class="modal fade" id="AddMasjidModel" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Add Event</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="Masjdadmodelbody">

            </div>

        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

@section scripts{



    <script>

        $(document).ready(function () {

            $('#example1').DataTable({
                "paging": true,
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": false,
            });

        });
        $("#btnAddmsjid").click(function () {
            //showLoading();
            $("#Masjdadmodelbody").load("/Events/AddEvent", function (e) {
                $("#AddMasjidModel").modal("show");
                //hideLoading();
            });
        });


        function ConfirmToDelete(id) {
            $('#deleteLink').click(function () {
                window.location.href = "/Events/Events/";
            });
            $('#ConfirmModal').show();
        }
        function ViewEdit(ID) {
            //showLoading();
            var url = "/Event/AddEvent?Id=" + 1;

            $("#Masjdadmodelbody").load(url, function (e) {
                var id = $('#MAsjid_ID').val();
                if (id > 0) {
                    $('#btnsavemasjid').html("update ");
                }
                $("#AddMasjidModel").modal("show");
                // hideLoading();
            });
        }

        function ShowProduct(ID) {
            //showLoading();
            var url = "/Events/AddEvent?Id=" + 1;

            $("#Masjdadmodelbody").load(url, function (e) {
                var id = $('#MAsjid_ID').val();
                if (id > 0) {
                    $('#btnsavemasjid').html("update ");
                }
                $("#AddMasjidModel").modal("show");
                // hideLoading();
            });
        }
    </script>
}

ACME/Views/Events/_AddEvent.cshtml
@model HrProperty.Models.FL_MASJID
@{
    Layout = null;
}
<div class="card-body">
    @*<form role="form" id="formaddtype">*@
    @using (Ajax.BeginForm("AddUpdate", "Masjid", FormMethod.Post, new AjaxOptions { OnSuccess = "OnSuccess", OnFailure = "OnFailure" }))
    {
        <div class="row">
            <div class="col-sm-6">
                <!-- text input -->
                <div class="form-group">
                    <label>Event Name:</label>
                    @Html.EditorFor(model => model.Masjid_Title, new { htmlAttributes = new { @placeholder = " Name", @class = "form-control" } })
                    @*<input type="text"  class="form-control" placeholder="@ViewBag.CustomerCode" disabled>*@
                </div>
                @Html.ValidationMessageFor(model => model.Masjid_Title, "", new { @class = "text-danger" })
            </div>
            <div class="col-sm-6">
                <!-- text input -->
                <div class="form-group">
                    <label>Event Location:</label>
                    @Html.EditorFor(model => model.Masjid_Location, new { htmlAttributes = new { @placeholder = " Location", @class = "form-control" } })
                    @*<input type="text"  class="form-control" placeholder="@ViewBag.CustomerCode" disabled>*@
                </div>
                @Html.ValidationMessageFor(model => model.Masjid_Location, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6">
                <!-- text input -->
                <div class="form-group">
                    <label>Event Date Urdu:</label>
                    @Html.EditorFor(model => model.DateCreated, new { htmlAttributes = new { @placeholder = "Lat", @class = "form-control" } })
                    @*<input type="text"  class="form-control" placeholder="@ViewBag.CustomerCode" disabled>*@
                </div>
                @Html.ValidationMessageFor(model => model.Masjid_Lat, "", new { @class = "text-danger" })


            </div>
            <div class="col-sm-6">
                <!-- text input -->
                <div class="form-group">
                    <label>Event Date Eng:</label>
                    @Html.EditorFor(model => model.DateCreated, new { htmlAttributes = new { @placeholder = "Long", @class = "form-control" } })
                    @*<input type="text"  class="form-control" placeholder="@ViewBag.CustomerCode" disabled>*@
                </div>
                @Html.ValidationMessageFor(model => model.Masjid_Lon, "", new { @class = "text-danger" })


            </div>
            @Html.HiddenFor(model => model.MAsjid_ID)
        </div>
        <div class="row">
            <div class="col-sm-12">
                <!-- text input -->
                <div class="form-group">
                    <label>Event Name in Urdu:</label>
                    @Html.EditorFor(model => model.Masjid_Descr, new { htmlAttributes = new { @placeholder = " Location", @class = "form-control" } })
                    @*@Html.TextAreaFor(model => model.Masjid_Descr, new { @area = "13", @class = "form-control" })*@
                    @*<input type="text"  class="form-control" placeholder="@ViewBag.CustomerCode" disabled>*@
                </div>
                @Html.ValidationMessageFor(model => model.Masjid_Lat, "", new { @class = "text-danger" })


            </div>
            
        </div>
        

                <div class="row">
                    <div class="col-sm-6">
                        <!-- text input -->
                        <div class="form-group">
                            <label>Upload Image:</label>
                            @* @Html.TextBoxFor(model => model.f, new { htmlAttributes = new { @placeholder = "Lat", @class = "form-control" } })*@
                            <input type="file" class="form-control" accept="image/*">
                        </div>



                    </div>

                </div>

                <div class="card-footer justify-content-between">
                    <div class="row col-md-12">

                        <div class="col-md-12">
                            <div class="float-right">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                @*<input type="submit" value="Submit" class="btn btn-primary" />*@
                                <input type="button" value="save" id="btnsavemasjid" class="btn btn-primary" />

                            </div>
                        </div>
                    </div>
                </div>

    }

</div>

<script>
    $("#btnsavemasjid").click(function () {
        Command: toastr["success"]("success", "Saved")

        toastr.options = {
            "closeButton": false,
            "debug": false,
            "newestOnTop": false,
            "progressBar": true,
            "positionClass": "toast-top-center",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
        window.location.href = "/Masjid/Masjid";
    });
</script>